name: echotype
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  http: ^1.2.2
  path_provider: ^2.1.4
  flutter_sound: ^9.7.0
  flutter_html: ^3.0.0-beta.2
  flutter_dotenv: ^5.2.1
  device_info_plus: ^11.4.0 
  record: ^6.0.0
  retry: ^3.1.2
  flutter_markdown: ^0.6.15
  markdown_widget: ^2.3.2+8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/microphone.png
    - assets/notes.png
    - assets/brainstorm.png
    - assets/robot.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
